image: node:10.17.0

cache:
  paths:
  - vendor/
  exclude:
  - vendor

pages:
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
